---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: release-me
- name: ci
- name: repo
- name: version
- name: resource-versions
  optional: true

outputs:
- name: built-notes

params:
  GITHUB_TOKEN:
  GITHUB_BRANCH:
  GITHUB_OWNER:
  GITHUB_REPO:

run:
  path: ci/tasks/scripts/build-release-notes
