---
platform: darwin

inputs:
- name: concourse
- name: ci
- name: version
- name: final-version
  optional: true
- name: fly-linux
- name: fly-windows
- name: fly-darwin

outputs:
- name: concourse-tarball

caches:
- path: gopath

params:
  PLATFORM: darwin

run:
  path: ci/tasks/scripts/concourse-build
