platform: linux

image_resource:
  type: registry-image-resource
  source: { repository: ubuntu }

inputs:
- name: version
  optional: true

outputs:
- name: dpkg-list

params:
  COMPONENT_NAME: ~
  VERSION: ~

run:
  path: /bin/bash
  args:
    - -cex
    - |
      if [[ -d ./version ]]; then
        VERSION=$(cat ./version/version)
      fi

      dpkg -l > ./dpkg-list/${COMPONENT_NAME}-dpkg-list-${VERSION}.txt
