---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  GCP_PROJECT:
  GCP_KEY:
  SSH_KEY:
  WORKSPACE: default
  CONCOURSE_VERSION: "dev"
  # variables consumed by terraform and their default values
  TF_VAR_GCP_IMAGE: "ubuntu-2004-lts"
  TF_VAR_RUNTIME: "guardian"
  TF_VAR_HAS_RUNTIME_FLAG: "true"

inputs:
- name: concourse
- name: ci
- name: linux-rc
  optional: true

outputs:
- name: outputs

run:
  path: ci/tasks/scripts/terraform-smoke
